spring:
  application:
    name: camel-microservice-a
  activemq:
    broker-url: tcp://localhost:61616
    user: admin        # adjust if you changed default credentials
    password: admin
camel:
  component:
    kafka:
      brokers: localhost:9092
server:
  port: 8080
